### PR TITLE
Save to localforage

### PR DESCRIPTION
**Pull request by jdungan**
I've put in all the pieces but it's not functional yet.  Ready for an intern to make it work.

### CODE REVIEW

**Comment by groovecoder** [comment]
Sorry I merged a PR that completely re-named this project to data-leak and expanded the scope. We'll need to rebase and update this.

**Comment by jdungan** [comment]
My head hurts thinking about rebasing this.  I'll just add and adjust the
files I contributed.

John

**Comment by jdungan** [comment]
is this what you had in mind?:

https://stackoverflow.com/questions/37471740/how-to-copy-commits-from-one-git-repo-to-another#37474065

**Comment by jdungan** [comment]
Or maybe the PR with a bit of clean up will do the trick.

**Comment by groovecoder** [comment]
A PR with a bit of cleanup should be fine.

**Comment by jdungan** [comment]
Going to start over and attack the open issues.  I'll keep the localforage stuff local in case we want to use it later.

**Pull request closed without merging**
